name: Daily NBA Data Update

on:
  schedule:
    # Runs at 12:00 UTC everyday (approx 5:30 PM IST / 7:30 AM ET)
    - cron: '0 12 * * *'
  workflow_dispatch: # Allows you to click a button to run it manually

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install pandas requests beautifulsoup4 nba_api pytz

      - name: Run Scraper
        run: python update_data.py

      - name: Commit and Push
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add nba_data.json
          git commit -m "Auto-update data" || echo "No changes to commit"
          git push